# Generated by rmake: do not edit by hand
SHELL=/bin/sh
R="$(R_HOME)/bin$(R_ARCH)/Rscript"
RM=del

.PHONY: all
all: Makefile data/FEDdata.rds fedapp/FEDdata.RDS
	
data/FEDdata.rds: data.R incoming/FEDdata.xlsx
	$(R) -e '{' \
	-e '    params <- list(.target = "data/FEDdata.rds", .script = "data.R", .depends = "incoming/FEDdata.xlsx", .task = "all")' \
	-e '    source("data.R")' \
	-e '}'
fedapp/FEDdata.RDS: evolving.R data/FEDdata.RDS incoming/data_for_evolving.xlsx
	$(R) -e '{' \
	-e '    params <- list(.target = "fedapp/FEDdata.RDS", .script = "evolving.R", .depends = c("data/FEDdata.RDS", "incoming/data_for_evolving.xlsx"), .task = "all")' \
	-e '    source("evolving.R")' \
	-e '}'
.PHONY: clean
clean: 
	$(RM) data/FEDdata.rds
	$(RM) fedapp/FEDdata.RDS
Makefile: Makefile.R
	$(R) -e '{' \
	-e '    params <- list(.target = "Makefile", .script = "Makefile.R", .depends = NULL, .task = "all")' \
	-e '    source("Makefile.R")' \
	-e '}'
